name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cleanup old files on VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            pm2 delete all || true
            rm -rf /var/www/andi-website

      - name: Upload files to VPS (Next.js + Strapi + DB)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: "."
          target: /var/www/andi-website

      - name: Write .env files on VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            echo "STRAPI_API_URL=${{ secrets.STRAPI_API_URL }}" > /var/www/andi-website/.env

            mkdir -p /var/www/andi-website/cms/.tmp

            cat <<EOF > /var/www/andi-website/cms/.env
            HOST=0.0.0.0
            PORT=1337
            APP_URL=https://cms.andi.zamora.ai
            PROXY_ENABLED=true
            NODE_ENV=production
            APP_KEYS=${{ secrets.STRAPI_APP_KEYS }}
            API_TOKEN_SALT=${{ secrets.STRAPI_API_TOKEN_SALT }}
            ADMIN_JWT_SECRET=${{ secrets.STRAPI_ADMIN_JWT_SECRET }}
            TRANSFER_TOKEN_SALT=${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }}
            ENCRYPTION_KEY=${{ secrets.STRAPI_ENCRYPTION_KEY }}
            DATABASE_CLIENT=sqlite
            DATABASE_FILENAME=/var/www/strapi-data/data.db
            JWT_SECRET=rLBfGErF6kb0iiYycCHuTg==
            EOF

      - name: Build & Restart apps on VPS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            set -e

            cd /var/www/andi-website

            echo "🔧 STEP 1: Install & Build Next.js"
            npm ci --legacy-peer-deps
            npm run build

            echo "🚀 STEP 2: Restart Next.js via PM2"
            pm2 delete next-app || true
            pm2 start "npm run start -- -p 3000 -H 0.0.0.0" --name next-app

            sleep 5

            echo "🛠 STEP 3: Install & Build Strapi"
            cd cms
            npm ci --legacy-peer-deps
            npm run build

            echo "🚀 STEP 4: Restart Strapi via PM2"
            pm2 delete strapi-app || true
            pm2 start "npm run start" --name strapi-app

            echo "💾 STEP 5: Save PM2 config"
            pm2 save

            echo "✅ ALL DONE"
